################################################################################
# Automatically-generated file. Do not edit!
################################################################################

ASM_SRCS := 
C_SRCS := 
OBJ_SRCS := 
O_SRCS := 
S_UPPER_SRCS := 
C_DEPS := 
EXECUTABLES := 
OBJS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
arch/arm/arm_cm3/drivers \
arch/arm/arm_cm3/drivers/STM32F10x_StdPeriph_Driver/src \
arch/arm/arm_cm3/drivers/STM32_ETH_Driver/src \
arch/arm/arm_cm3/kernel \
arch/arm/arm_cr4/drivers \
arch/arm/arm_cr4/kernel \
arch/generic/linux/drivers \
arch/generic/linux/kernel \
arch/hc1x/hcs12d/drivers \
arch/hc1x/hcs12d/kernel \
arch/ppc/mpc55xx/drivers \
arch/ppc/mpc55xx/integration \
arch/ppc/mpc55xx/kernel \
arch/ppc/mpc55xx/mm \
boards/generic \
boards/hcs12_elmicro_card12/examples/blinker \
boards/hcs12_elmicro_card12/examples/blinker/config \
boards/hcs12_elmicro_card12/examples/os_simple/config \
boards/hcs12x_elmicro_tboard/examples/ledmaster \
boards/hcs12x_elmicro_tboard/examples/ledmaster/config \
boards/hcs12x_elmicro_tboard/examples/os_simple/config \
boards/mpc5516it/config \
boards/mpc5516it/examples/com_simple \
boards/mpc5516it/examples/com_simple/config \
boards/mpc5516it/examples/led_rte \
boards/mpc5516it/examples/led_rte/config \
boards/mpc5516it/examples/os_simple/config \
boards/mpc551xsim/examples/os_schtbl/config \
boards/mpc551xsim/examples/os_schtbl \
boards/mpc551xsim/examples/os_simple/config \
boards/mpc5567qrtech/config \
boards/mpc5567qrtech/examples/led_rte \
boards/mpc5567qrtech/examples/led_rte/config \
boards/mpc5567qrtech/examples/os_simple/config \
boards/mpc5567qrtech/examples/rte_simple/config \
boards/mpc5602b_xpc560b/config \
boards/mpc5602b_xpc560b/examples/lin_simple \
boards/mpc5602b_xpc560b/examples/lin_simple/config \
boards/mpc5602b_xpc560b/examples/os_simple/config \
boards/mpc5604b_trk/config \
boards/mpc5604b_trk/examples/os_simple/config \
boards/mpc5604p_trk/config \
boards/mpc5604p_trk/examples/os_simple/config \
boards/mpc5606b_xpc560b/config \
boards/mpc5606b_xpc560b/examples/os_simple/config \
boards/mpc5606s_xpc560s/config \
boards/mpc5606s_xpc560s/examples/os_simple/config \
boards/mpc5634m_trk/config \
boards/mpc5634m_trk/examples/os_simple/config \
boards/mpc5668_gkit/config \
boards/mpc5668_gkit/examples/os_simple/config \
boards/stm32_mcbstm32/examples/os_simple/config \
boards/stm32_stm3210c/examples/com_simple \
boards/stm32_stm3210c/examples/com_simple/config \
boards/stm32_stm3210c/examples/com_simple/obj_stm32_stm3210c \
boards/stm32_stm3210c/examples/os_simple/config \
boards/stm32_stm3210c/examples/os_simple/obj_stm32_stm3210c \
boards/stm32_stm3210c/examples/os_simple \
boards/ti_tms570ls/examples/os_simple/config \
boards/ti_tms570ls/examples/rte_simple/config \
clib \
common \
common/tcf \
communication/CanIf \
communication/CanNm \
communication/CanSM \
communication/CanTp \
communication/Com \
communication/ComM \
communication/J1939Tp \
communication/Lin \
communication/Nm \
communication/PduR \
diagnostic/Dcm \
diagnostic/Dem \
diagnostic/Det \
drivers \
examples/os_simple_orig \
examples/rte_simple \
examples \
learn_in_depth_labs/stm32_stm3210c/labs/LearnInDepth_lab1 \
learn_in_depth_labs/stm32_stm3210c/labs/LearnInDepth_lab1/config \
learn_in_depth_labs/stm32_stm3210c/labs/LearnInDepth_lab1/obj_stm32_stm3210c \
learn_in_depth_labs/stm32_stm3210c/labs/LearnInDepth_lab_clean \
learn_in_depth_labs/stm32_stm3210c/labs/LearnInDepth_lab_clean/config \
learn_in_depth_labs/stm32_stm3210c/labs/LearnInDepth_lab_clean/obj_stm32_stm3210c \
. \
memory/Ea \
memory/Fee \
memory/MemIf \
memory/NvM \
rte \
system/Crc \
system/EcuM \
system/IoHwAb \
system/SchM \
system/WdgIf \
system/WdgM \
system/kernel \
system/mm \

